version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: nest_postgres_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432" # Mappa la porta del container sul tuo PC
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: